language: cpp

env:
  matrix:
    # gcc default build
    - CC=gcc CXX=g++
    # clang default build
    - CC=clang CXX=clang++

before_script:
  - mkdir build && cd build && ../configure --enable-speedtest

script:
  - make -j4