language: cpp

env:
  matrix:
    # gcc default build
    - CC=gcc CXX=g++
    # clang default build
    - CC=clang CXX=clang++

    # build with older gcc
    - CC=gcc-4.6 CXX=g++-4.6

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - if [ "$CXX" == "g++-4.6" ]; then sudo apt-get install g++-4.6; fi

before_script:
  - mkdir build && cd build && ../configure --enable-speedtest

script:
  - make -j4